
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Footer from "./componentes/Footer";
import Header from "./componentes/Header";

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        <Header/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
          {children}
        <Footer/>
      </body>
    </html>
  );
}
